// Server component wrapper for the /ad-agency-visibility paid funnel.
// page.js is a client component (like app/page.js and app/schedule/page.js),
// so per-route metadata lives here. The OG / Twitter images are generated by
// opengraph-image.js / twitter-image.js in this folder.

const TITLE = 'Stop Burning 20+ Hours a Week on Client Reports';
const DESCRIPTION =
  'Fractional ad data infrastructure for agencies running 100K+/month across Meta and Google. One system. One dashboard. Every client.';

// Vercel injects VERCEL_PROJECT_PRODUCTION_URL automatically — nothing to set.
// metadataBase lets Next resolve the generated OG image to an absolute URL.
const SITE_URL = process.env.VERCEL_PROJECT_PRODUCTION_URL
  ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
  : 'http://localhost:3000';

export const metadata = {
  metadataBase: new URL(SITE_URL),
  title: `${TITLE} | DataStaq AI`,
  description: DESCRIPTION,
  // Paid funnel — keep it out of organic search.
  robots: { index: false, follow: false },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function AdAgencyVisibilityLayout({ children }) {
  return children;
}
