import Script from 'next/script';
import { DM_Sans } from 'next/font/google';
import './globals.css';
import MetaPageView from './components/MetaPageView';

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-jakarta',
  display: 'swap',
});

const META_PIXEL_ID = '1983404682281698';
const GA4_MEASUREMENT_ID = 'G-WDVFGBG0EH';

// Site-wide metadata. The home page (app/page.js) is the Fractional Ad
// Visibility funnel, so the default title/description/OG describe that.
// OG + Twitter images are generated by app/opengraph-image.js and
// app/twitter-image.js. Vercel injects VERCEL_PROJECT_PRODUCTION_URL
// automatically — metadataBase resolves the generated image to an absolute URL.
const SITE_URL = process.env.VERCEL_PROJECT_PRODUCTION_URL
  ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
  : 'http://localhost:3000';

const TITLE = 'Stop Burning 20+ Hours a Week on Client Reports';
const DESCRIPTION =
  'Fractional ad data infrastructure for agencies running 100K+/month across Meta and Google. One system. One dashboard. Every client.';

export const metadata = {
  metadataBase: new URL(SITE_URL),
  title: `${TITLE} | DataStaq AI`,
  description: DESCRIPTION,
  icons: {
    icon: [
      { url: '/favicon-32.png', sizes: '32x32', type: 'image/png' },
      { url: '/favicon-16.png', sizes: '16x16', type: 'image/png' },
    ],
    apple: '/apple-touch-icon.png',
  },
  openGraph: {
    title: TITLE,
    description: DESCRIPTION,
    type: 'website',
  },
  twitter: {
    card: 'summary_large_image',
    title: TITLE,
    description: DESCRIPTION,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={dmSans.variable}>
      <body className="font-jakarta antialiased">
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA4_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga4-init" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '${GA4_MEASUREMENT_ID}');`}
        </Script>
        <Script id="meta-pixel" strategy="afterInteractive">
          {`!function(f,b,e,v,n,t,s)
{if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};
if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];
s.parentNode.insertBefore(t,s)}(window, document,'script',
'https://connect.facebook.net/en_US/fbevents.js');
fbq('init', '${META_PIXEL_ID}');`}
        </Script>
        <noscript>
          <img
            height="1"
            width="1"
            style={{ display: 'none' }}
            src={`https://www.facebook.com/tr?id=${META_PIXEL_ID}&ev=PageView&noscript=1`}
            alt=""
          />
        </noscript>
        <MetaPageView />
        {children}
      </body>
    </html>
  );
}
